[build]
  # Create a simple build that copies the main files to build directory
  command = "mkdir -p build && cp index.html build/ && cp -r server build/ 2>/dev/null || true"
  # Publish from the build directory to match Netlify UI expectations
  publish = "build"

[build.environment]
  # Disable npm install since we don't need it for static HTML
  NPM_FLAGS = "--no-optional"

[[redirects]]
  # Redirect all routes to index.html for single-page app behavior
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true
